apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziglb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ziglb-operator
  template:
    metadata:
      labels:
        app: ziglb-operator
    spec:
      serviceAccountName: ziglb-operator
      containers:
        - name: ziglb-operator
          image: ziglb-operator:latest
          imagePullPolicy: Never
