log stderr all;
router id 172.18.255.1;
protocol device {
    scan time 60;
}
protocol kernel {
    merge paths;
    ipv4 {
        export filter {
            if source = RTS_DEVICE then reject;
            accept;
        };
    };
}
template bgp bgpnode {
    local as 65000;
    direct;
    passive;

    ipv4 {
        import all;
        export none;
    };
}
protocol bgp 'node0' from bgpnode {
    neighbor 172.18.0.2 as 65001;
}
protocol bgp 'node1' from bgpnode {
    neighbor 172.18.0.3 as 65001;
}
