apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ziglb-agent
spec:
  selector:
    matchLabels:
      app: ziglb-agent
  template:
    metadata:
      labels:
        app: ziglb-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: ziglb-agent
      containers:
        - name: ziglb-agent
          image: ziglb-agent:latest
          imagePullPolicy: Never
          env:
            - name: AS_NUMBER
              value: "65001"
            - name: ROUTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PEER_AS_NUMBER
              value: "65000"
            - name: PEER_ADDR
              value: "172.18.255.1"
