apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-debug
  template:
    metadata:
      labels:
        app: watch-debug
    spec:
      containers:
        - name: sleeper
          image: busybox:latest
          command: ["sh", "-c", "sleep infinity"]
